### ISSUE TITLE
Image decoupled from the image filename in source code on staging but not in dev

### ISSUE THREAD

**Issue by mpitblado** [gbif/hp-beaty-biodiversity-museum#3]
## Summary

Commit 9627575 fixed image file names in the `assets/image/` directory, however the new name does not appear to be associated with the image displayed on the staging site. Running on localhost, the images are correctly associated, and within the source code clicking on the image filename brings up the right image, however the image previously associated with the filename is displayed on staging. 

### On Localhost
In the screenshot below, taken on localhost, the orange highlighted area indicates where the cursor was placed at the time of taking the screenshot. Hovering over the image, we can see that the moth is associated with filename `treasure-59.png`. **This is the correct association**.

![localhost_image_association](https://github.com/gbif/hp-beaty-biodiversity-museum/assets/116753126/8200306f-3ed5-470f-9ba2-c07eee8e1b47)

### On Staging
On staging, however, we can see that `treasure-59.png` is instead associated with the image of the salmon. This was a previous association, but was corrected with commit 9627575. **This is not the correct association**, however does not seem to be able to be corrected by making changes to the source code.

![staging_image_association](https://github.com/gbif/hp-beaty-biodiversity-museum/assets/116753126/8dc379b8-c044-4555-ad33-2de4f556171b)

## Hypothesis
Could this be related to the build process somehow caching the old image, and therefore not changing the association? Or perhaps some part of the compression or build process undertook by Jenkins?

**Comment by MortenHofft** [comment]
Yes, if you change the content of an image, but keep the filename, then it will ruin caching. Sooner or later it will show the correct image. But I would suggest you use a new filename instead of changing the content of the image file. 

All or most images on the website go through a cache, where we scale, crop (depending on where it is used) and store it for a while. We also set cache headers that allow it to be stored in the browser.

So in this case it could be cached either server side or in your browser. If it is the later, then it is only you who sees a bedated version. You can test that by opening in a private window.

I see the image jar btw. So the server cache is up to date again. Looking at the browser cache header it seems it is stored an hour in the browser.

**Comment by MortenHofft** [comment]
I've added a data file called images. You do not have to use it and can simply delete it again if you prefer. 
The idea is that you can then reuse your images and titles across the long list and the individual pages.

So when you want to change the images (as in this case) or the title, then you do it one place and the changes apply to all the places you have used that "image". 
I created an example for treasure 59

**Comment by mpitblado** [comment]
Resolved by 3148f82
