### ISSUE TITLE
Dataset views

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-beaty-biodiversity-museum#4]
Hi @mpitblado 
I believe you asked at our last meeting if we could add dataset pages. We now have dataset detail pages and dataset search.
Let me know if this is something you would like to add, then I'm happy to help.

example page: https://hp-theme.gbif-staging.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c

That said, it isn't obvious (to me at least), that it isn't just confusing adding datasets as well. We often get the feedback that users struggle with the difference between a collection and a datasets (and institution/publisher).

**Comment by mpitblado** [comment]
Hi @MortenHofft, thanks for letting me know this is awesome! I agree that datasets/collections can be confusing (even explaining to other staff here at the museum). I think that we might end up using them though just because of how our institution is setup. We're going through a lot of (positive) change at the moment in data organization.

I see it also has an images carousel and a citations section! Definitely will use those citation pages as opposed to the pages I had implemented with the gbif citation widget, just a lot cleaner.
